env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
    - SKIP_NODE_SASS_TESTS = true

matrix: 
  include: 
    - language: node_js
      node_js: 
        - "node"
      dist: trusty
      sudo: required

      before_install:
        - cd spa

      install:
        - npm install
      cache: npm

      script: 
        - npm run build

    - language: csharp
      mono: none
      dotnet: 2.1.401

      install:
        - cd API
        - dotnet restore

      script:
        - dotnet build

