matrix: 
  include: 
    - language: node_js
      node_js: 
        - "6"
      dist: trusty
      sudo: required

      before_install:
        - cd spa

      install:
        - npm install
      cache:
        directories:
          - "$HOME/spa/.npm"
          - "spa/node_modules"

      script: 
        - npm run build

    - language: csharp
      mono: none
      dotnet: 2.1.401

      install:
        - cd API
        - dotnet restore

      script:
        - dotnet build

