matrix: 
  include: 
    - language: node_js
      node_js:
      - "8.11"

      branches:
        only:
          - master

      addons:
        chrome: stable

      before_script:
        - yarn global add @angular/cli

      cache:
        yarn: true
        directories:
          - node_modules

      script:
      - ng build --prod

    - language: csharp
      mono: none
      dotnet: 2.1.401

      install:
        - cd API
        - dotnet restore

      script:
        - dotnet build

