matrix: 
  include: 
    - language: csharp
      mono: none
      dotnet: 2.1.401

      install:
        - cd API
        - dotnet restore

      script:
        - dotnet build

    - language: node_js
      node_js: 
        - "node"
      dist: trusty
      sudo: required
      
      install:
        - npm install
      cache:
        directories:
          - "$HOME/.npm"
          - "node_modules"

      script: 
        - npm run build