matrix: 
  include: 
- language: csharp
    mono: none
    dotnet: 2.0.0

    install:
      - cd API
      - dotnet restore

    before_script: cd ../API.TESTS/

    script:
    - dotnet test

  - language: node_js
    node_js: 
      - "8"

    before_script:
      - cd angular-unit-testing
      - npm install -g @angular/cli

    script:
      - ng build --prod --aot
      - ng test
