matrix: 
  fast_finish: true

  include: 
    - language: node_js
      sudo: false
      node_js: 
        - "node"

      install:
        - cd spa
        - npm install --no-progress
      cache: npm

      script: 
        - npm run build

    - language: csharp
      mono: none
      dotnet: 2.1.401

      install:
        - cd API
        - dotnet restore

      script:
        - dotnet build

