matrix: 
  include: 
    - language: node_js
      node_js: 
        - "node"
      dist: trusty
      sudo: required

      addons:
        chrome: stable

      before_script:
        - ls
        - cd SPA
        - npm install -g @angular/cli

      script:
        - ng build --prod --aot

    - language: csharp
      mono: none
      dotnet: 2.0.0

      install:
        - cd API
        - dotnet restore

      script:
      - dotnet build

  notifications:
    email: false

  branches: 
    only:
      - master
      - develop
