matrix: 
  include: 
    - language: node_js
      node_js: 
        - "node"
      dist: trusty
      sudo: required

      addons:
        chrome: stable

      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      before_script:
        - "sudo chown root /usr/lib/chromium-browser/chrome-sandbox"
        - "sudo chmod 4755 /usr/lib/chromium-browser/chrome-sandbox"
        - npm install -g @angular/cli
        - ng update @angular/cli --migrate--only --from=1.7.4

      script:
        - cd SPA
        - ng build --prod --aot

    - language: csharp
      mono: none
      dotnet: 2.0.0

      install:
        - cd API
        - dotnet restore

      script:
      - dotnet build

  notifications:
    email: false

  branches: 
    only:
      - master
      - develop
