matrix: 
  include: 
    - language: node_js
      node_js: 
        - "9"
      dist: trusty
      sudo: required
      
      
      cache:
        directories:
          - node_modules

      addons:
        chrome: stable

      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      before_script:
        - "sudo chown root /usr/lib/chromium-browser/chrome-sandbox"
        - "sudo chmod 4755 /usr/lib/chromium-browser/chrome-sandbox"
        - cd spa
        - npm i -g @angular/cli
        - npm ci
        - ng update @angular/cli --migrate--only --from=1.7.4

      script:
        - ng build

    - language: csharp
      mono: none
      dotnet: 2.0.0

      install:
        - cd API
        - dotnet restore

      script:
        - dotnet build