matrix: 
  include: 
    - language: csharp
      mono: none
      dotnet: 2.0.0

      install:
        - cd API
        - dotnet restore

      before_script: cd ../API.TESTS/

      script:
      - dotnet test

    - language: node_js
      node_js: 
        - "node"
      dist: trusty

      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      before_script:
        - cd angular-unit-testing
        - npm install -g @angular/cli
        - ng update @angular/cli --migrate--only --from=1.7.4

      script:
        - ng build --prod --aot
        - ng test --watch=false
